### ISSUE TITLE
Error when building with debug enabled

### ISSUE THREAD

**Issue by CEBeard3** [avadhpatel/marss#52]
When trying to build with the debug flag enabled I am getting this error:
error: use of deleted function 'YAML::Emitter& YAML::Emitter::operator=(const YAML::Emitter&)'
in ptlsim/build/tests/stats-tests.cpp, I am unsure if this is why I am getting no output to my stats file but I feel like this is a problem. Any advice on how to solve this issue would be appreciated.

**Comment by fitzfitsahero** [comment]
When I updated the YAML code to c++11 I never bothered to touch the stats-tests code. 

Clean your build, move or delete stats-tests.cpp, then build again. That should fix the issue

**Comment by CEBeard3** [comment]
Thank you, that solved the issue
