### ISSUE TITLE
Disk Image Issue

### ISSUE THREAD

**Issue by CEBeard3** [avadhpatel/marss#53]
I'm not sure if this should go here but I couldn't find another place to post.
I am trying to run marss with the parsecROI.img file from the Disk Images page on the Marssx86 site. When I attempt to build the parsec-2.1 benchmarks with parsecmgmt I get:
env: /usr/bin/make: No such file or directory 
and the build fails. Has anyone else run into this problem and if so is there a known solution?

Thanks and if I am missing something simple I sincerely apologize for cluttering up this page.

**Comment by fitzfitsahero** [comment]
Those images have been stripped down, so things like make, gcc, build-essential, are not installed.

There already are benchmarks built, and you can see how to run them by looking at the create_checkpoints.py script in util/ in the marss directory. Or you can play around with parsecmgmt more to figure out how to run them through that utility.
