### ISSUE TITLE
machine configuration 

### ISSUE THREAD

**Issue by xubaqian** [avadhpatel/marss#59]
I don't know how to configure the simulated CPU with a 64-entry instructions TLB and 64-entry data TLB.

Besides,  I try to configure it with a 96-entry issue queue, and add the following code in  conf/ooo_core.conf

> core:
  ooo:
    base: ooo 
    params:
      ISSUE_Q_SIZE: 96

But an error occurs when simulating ls command:

> qemu-system-x86_64: ptlsim/build/core/ooo-core/ooo-exec.cpp:186: bool ooo::IssueQueue<size, operandcount>::insert(ooo::IssueQueue<size, operandcount>::tag_t, const tag_t*, const tag_t*) [with int size = 96; int operandcount = 4; ooo::IssueQueue<size, operandcount>::tag_t = short unsigned int]: Assertion `!bit(valid, slot)' failed.

It seems 96 entries are too large. Any suggestions would be appreciated.

**Comment by fitzfitsahero** [comment]
The file ooo-const.h has all the defines to change sizes of various units in the pipeline. 

You'd have to debug to see why that assert is being thrown.
